name: BUILD_WORKFLOW_DEMO

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use my composite action
        uses: ./.github/actions/my-actions          