name: BUILD_WORKFLOW_DEMO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        uses: ./actions/my-actions
        with:
          node-version: '18'
