
name: My first Workflow
on: 
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: ikc3kor
    IMAGE_NAME: github-actions-ngnix

jobs:
    
    first_job:
        runs-on: labvm2g8
        steps:
            - uses: actions/checkout@v4
            - name: Welcome
              run: echo "My first github actions job"
            - name: List files
              run: ls
            - name: Test the env variables
              run: |
                  echo ${DOCKER_USERNAME}
                  echo ${{secrets.REPOSECRET}}
                  echo ${{vars.REPOVAR1}}

            - name: script executable perm
              run: |
                chmod +x hello.sh
                chmod +x ascii-script.sh
            - name: script
              run: |
                ./hello.sh
                ./ascii-script.sh
            - name: Upload dragon file to artifact
              uses: actions/upload-artifact@v4.6.2
              with:
                  name: dragon-text-file
                  path: dragon.txt
            - name: Pause for 30 seconds
              run: sleep 15

    second_job:
        runs-on: labvm2g8
        needs:  first_job
        steps:
            - name: Welcome
              run: echo "My Second github actions job"
            - name: Pause for 10 seconds
              run: sleep 10
            - name: Download dragon file to artifact
              uses: actions/download-artifact@v5.0.0
              with:
                  name: dragon-text-file
            - name: Verify dragon.txt
              run: grep -i "dragon" dragon.txt
            
            