
name: My first Workflow
on: push

jobs:
    first_job:
        runs-on: labvm2g8
        steps:
            - uses: actions/checkout@v4
            - name: Welcome
              run: echo "My first github actions job"
            - name: List files
              run: ls
            - name: script executable perm
              run: |
                chmod +x hello.sh
                chmod +x ascii-script.sh
            - name: script
              run: |
                ./hello.sh
                ./ascii-script.sh
            - name: Pause for 30 seconds
              run: sleep 30

    second_job:
        runs-on: labvm2g8
        needs:  first_job
        steps:
            - name: Welcome
              run: echo "My Second github actions job"
            - name: Pause for 10 seconds
              run: sleep 10
            - name: Verify dragon.txt
              run: grep -i "dragon" dragon.txt
            
            