
name: Workflow for develop2
on: 
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
    first_job:
        runs-on: labvm2g8
        steps:
            - uses: actions/checkout@v4
            - name: Welcome
              run: echo "My first github actions job"
            - name: List files
              run: |
                ls -ltra
                echo "Test"
          